### ISSUE TITLE
Issue with execution of DetectPSVs.py

### ISSUE THREAD

**Issue by Shyamasundar** [siddiqaa/psvcounter#1]
Followed your beautiful guidance.

Everything is working till DetectPSVs.py . It has a function detect_objects, which is not called anywhere from outside. Can you please give me some hints to finish my final stage. 

Done till export_inference_graph successfully.

**Comment by siddiqaa** [comment]
Looks like there was an indentation issue in DetectPSVs.py. I updated the code. Try using the updated script
